/*******************************************************************************
 * LEGAL DISCLAIMER
 *
 * (Header of MediaTek Software/Firmware Release or Documentation)
 *
 * BY OPENING OR USING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND
 * AGREES THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK
 * SOFTWARE") RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO
 * BUYER ON AN "AS-IS" BASISONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
 * NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH
 * RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 * INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO
 * LOOK ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO.
 * MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES
 * MADE TO BUYER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN
 * FORUM.
 *
 * BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
 * LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE WITH
 * THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF LAWS
 * PRINCIPLES.
 ******************************************************************************/

/* FILE NAME:  bt_mw_msg.h
 * AUTHOR: Changlu Yi
 * PURPOSE:
 *      It provides bluetooth common structure to MSG.
 * NOTES:
 */

#ifndef __LINUXBT_MSG_H__
#define __LINUXBT_MSG_H__

#include "u_bluetooth.h"

#define MAX_BT_MSG_LEN    128
#define LINUXBT_QUEUE_NUM    16
#define BT_MSG_ID    '0'

#define LINUXBT_MSG_PREFIX    PLATFORM_LIB_PATH"/libaudio.a2dp.default.so"
#define LINUXBT_RECV_MSG_ALL    0



typedef enum
{
    LINUXBT_MSG_FROM_WRAP = 1,

    LINUXBT_MSG_MAX
}LINUXBT_MSG_TYPE;

//typedef long IPC_MSG_TYPE;
typedef struct _LINUXBT_BODY_T
{
    LINUXBT_EVT_TYPE evtType;
    INT32 len;
    UINT8 data[MAX_BT_MSG_LEN];
}LINUXBT_BODY_T;

typedef struct _LINUXBT_MSG_T
{
    long tMsgType;   //IPC_MSG_TYPE
    LINUXBT_BODY_T body;
}LINUXBT_MSG_T;

typedef struct _LINUXBT_QUEUE_T
{
    UINT8 currLen;
    UINT8 maxLen;
    UINT8 head;
    LINUXBT_MSG_T* msg[LINUXBT_QUEUE_NUM];
}LINUXBT_QUEUE_T;

extern INT32 i4LinuxBtSendMsg(LINUXBT_MSG_T* msg);

extern INT32 linuxbt_msg_queue_init(VOID);

#endif/*__LINUXBT_MSG_H__*/
