/********************************************************************************************
 *     LEGAL DISCLAIMER
 *
 *     (Header of MediaTek Software/Firmware Release or Documentation)
 *
 *     BY OPENING OR USING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 *     THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE") RECEIVED
 *     FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON AN "AS-IS" BASIS
 *     ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED,
 *     INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR
 *     A PARTICULAR PURPOSE OR NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY
 *     WHATSOEVER WITH RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 *     INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK
 *     ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
 *     NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S SPECIFICATION
 *     OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
 *
 *     BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE LIABILITY WITH
 *     RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION,
 *     TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE
 *     FEES OR SERVICE CHARGE PAID BY BUYER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 *     THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE WITH THE LAWS
 *     OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF LAWS PRINCIPLES.
 ************************************************************************************************/
#ifndef _C_MW_CONFIG_H_
#define _C_MW_CONFIG_H_

#include "u_bt_mw_types.h"
//for bluetooth config

#define ENABLE_INTERNAL_SUSPEND 1
#define DISPATCH_A2DP_WITH_PLAYBACK 1
#define DISCARD_DATA_BEFORE_PLAY 1
#define ENABLE_SPP_PROFILE 0
#define ENABLE_HID_PROFILE_H 1
#define ENABLE_HID_PROFILE_D 0
#define ENABLE_GATT_PROFILE 1
#define ENABLE_AVRCP_PROFILE 0
#define ENABLE_ALWAYS_CONNECTABLE_MODE 1
#define ENABLE_A2DP_SRC 1
#define ENABLE_A2DP_MC_UPLD 1
#define ENABLE_A2DP_SINK 1
#define ENABLE_AAC_CODEC 0
#define ENABLE_LDAC_CODEC 0
#define ENABLE_APTX_CODEC 0
#define ENABLE_SAVE_LOCAL_DEV_TO_FILE 1
#define ENABLE_SHOW_SCREEN 1
#define ENABLE_BUFFER_CONTROL 0
#define ENABLE_TRACK_EXCHANGE 0
#define ENABLE_A2DP_ALSA_CLOSE_ALIGN_DISC 0
#define ENABLE_HERCULES 1
#define MTK_BLE_GGL_SETUP_SUPPORT 0

#endif //_C_MW_CONFIG_H_
