/*******************************************************************************
 * LEGAL DISCLAIMER
 *
 * (Header of MediaTek Software/Firmware Release or Documentation)
 *
 * BY OPENING OR USING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND
 * AGREES THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK
 * SOFTWARE") RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO
 * BUYER ON AN "AS-IS" BASISONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
 * NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH
 * RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 * INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO
 * LOOK ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO.
 * MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES
 * MADE TO BUYER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN
 * FORUM.
 *
 * BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
 * LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE WITH
 * THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF LAWS
 * PRINCIPLES.
 ******************************************************************************/

/* FILE NAME:  bt_mw_msg.h
 * AUTHOR: Changlu Yi
 * PURPOSE:
 *      It provides bluetooth common structure to MSG.
 * NOTES:
 */

#ifndef __BT_MW_MSG_H__
#define __BT_MW_MSG_H__

#include "u_bluetooth.h"
#include "bt_mw_common.h"

#define MAX_BT_MSG_LEN    128
#define BT_MSG_QUEUE_NUM    16
#define BT_MSG_ID    '0'

#define BT_MSG_PREFIX    PLATFORM_LIB_PATH"/libbluetooth.default.so"

#define BT_RECV_MSG_ALL    0
#define BT_SOCK_NAME_MSG_SEND_MW BT_TMP_PATH"/bt.app.msg.send"
#define BT_SOCK_NAME_MSG_RECV_MW BT_TMP_PATH"/bt.app.msg.recv"

#define BT_FREE(x)    { if(x != NULL)  free(x); x=NULL; }

typedef enum
{
    BT_MSG_FROM_MW = 1,

    BT_MSG_MAX
}BT_MSG_TYPE;

//typedef long IPC_MSG_TYPE;
typedef struct _BT_BODY_T
{
    BT_EVT_TYPE evtType;
    INT32 len;
    UINT8 data[MAX_BT_MSG_LEN];
}BT_BODY_T;

typedef struct _BT_MSG_T
{
    long tMsgType;   //IPC_MSG_TYPE
    BT_BODY_T body;
}BT_MSG_T;

typedef struct _BT_QUEUE_T
{
    UINT8 currLen;
    UINT8 maxLen;
    UINT8 head;
    BT_MSG_T* msg[BT_MSG_QUEUE_NUM];
}BT_QUEUE_T;

extern INT32 i4SendMsg(BT_MSG_T* msg);

extern INT32 bt_msg_queue_init(VOID);

#endif/* __BT_MW_MSG_H__ */
